# Generated by Django 2.2.7 on 2019-11-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='COD_BARR',
            field=models.CharField(max_length=15, verbose_name='Codigo de Barras'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='DESCRIC',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='EMBALAGEM',
            field=models.CharField(max_length=10, verbose_name='Embalagem'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='TAGS',
            field=models.CharField(max_length=240, verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='UM',
            field=models.CharField(max_length=3, verbose_name='Unidade de Medida'),
        ),
    ]
