# Generated by Django 2.2.7 on 2019-11-29 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191129_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='COD_BARR',
        ),
    ]
