# Generated by Django 2.2.7 on 2019-11-29 14:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_produto_cod_barr'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='COD_BARR',
            field=models.CharField(default=datetime.datetime(2019, 11, 29, 14, 32, 57, 76150, tzinfo=utc), max_length=15, verbose_name='Codigo de Barras'),
            preserve_default=False,
        ),
    ]
